Metrics 0.23
ramn/metrics_cloudwatch pull request #49
Opened 2024-06-11 08:11 UTC by john-eriksson-imperva

2024-12-10 04:24 UTC, jregistr commented
This closes: https://github.com/ramn/metrics_cloudwatch/issues/45

2024-12-11 15:50 UTC, Marwes requested changes

2024-12-11 15:50 UTC, Marwes commented on src/collector.rs
> +        metrics::Counter::from_arc(Arc::new(RecorderHandleKey {
This effectively creates temporary allocations in the typical usage like

```rust
metrics::counter!("test").increment(1);
```
which is going to be horrible for perfomance. We need to cache these handles to amortize the cost to make it berable. `metrics_util` has https://docs.rs/metrics-util/latest/metrics_util/registry/struct.Registry.html for this but I am not quite sure how we could use that while having time bucketed metrics to report to cloudwatch so either our own cache or maybe `metrics_util` could be extended https://github.com/metrics-rs/metrics/issues/546

2024-12-17 11:44 UTC, zekehuntergreen commented
Glad to see this is so close! I'm hoping to use [axum-metrics](https://docs.rs/axum-metrics/latest/axum_metrics/) with metric-cloudwatch and the differing versions of `metrics` is causing problems.

2024-12-30 13:10 UTC, OliverGavin commented
any way to move this forward?

2025-01-10 16:47 UTC, agasparovic commented
Re: the comment on performance above - I ran the benchmarks from v3.0.0 vs. this change. Looks like a difference of 55 microseconds (221 before vs 276 after).

If that's acceptable could this be merged to unblock everyone trying to upgrade metrics, and then come back and figure out how to cache after?

2025-01-16 11:16 UTC, merged